image: bradrydzewski/go:1.3
script:
  - echo "make test"
publish:
  github:
    script:
      - echo "make release"
      - mkdir release
      - echo "asdf" > release/asdf.txt
      - echo "qwer" > release/qwer.txt
    artifacts:
      - release
    tag: $(cat VERSION)
    token: {{github_token}}
    user: rgarcia
    repo: test
